### ISSUE TITLE
orc_write ETA

### ISSUE THREAD

**Issue by dohongdayi** [qubole/spark-acid#11]
Great work!

May I know the ETA of orc_write feature?

**Comment by somani** [comment]
Hey!

Thanks for your interest! We expect to be done with ORC writes by the end of September.

**Comment by dohongdayi** [comment]
Thanks !

Any news?

**Comment by citrusraj** [comment]
https://github.com/qubole/spark-acid/commit/2e66f76b3a3c974a73f03d9e80d9c66a0475a552

Merge and Bucketed support being worked on.
