### ISSUE TITLE
ACID removing data

### ISSUE THREAD

**Issue by aemanukyan** [qubole/spark-acid#13]
Hey everybody. I have problem with removing data from HDFS with spark (hive context) so I have question, is your library support ACID removing in sparksql (hive context) from HDFS ?

**Comment by somani** [comment]
Hey can you clarify what you mean by removing data? If you mean you want to run delete or update selected rows of data, then yes ACID will let you do that.

**Comment by aemanukyan** [comment]
@somani Yes I mean delete/update some rows. Thanks!
