### ISSUE TITLE
Support explicit catalog name when specifying an acid table

### ISSUE THREAD

**Issue by somani** [qubole/spark-acid#15]
On HDP, Spark by default uses a different catalog(than hive on HDP) with the name "spark". We should support catalog names as well in our datasource, so that the user can specify which catalog the table exists in.

https://github.com/qubole/spark-acid/issues/12 for reference.

**Comment by citrusraj** [comment]
Bundled as part of https://github.com/qubole/spark-acid/pull/30

**Comment by citrusraj** [comment]
https://github.com/qubole/spark-acid/commit/2e66f76b3a3c974a73f03d9e80d9c66a0475a552
