### ISSUE TITLE
Handle task retries gracefully in Spark ACID OSS

### ISSUE THREAD

**Issue by amoghmargoor** [qubole/spark-acid#43]
Tasks writing data into Hive ACID if failed then would be retried like normal Spark Tasks. But if failed task would have created bucket file under delta directory, then new task would fail like specified in this issue: #41

In Qubole's Hive fork are overwriting the file instead of throwing error and hence things work. We need to solve this for Open source.

**Comment by sourabh912** [comment]
@amoghmargoor : Currently, does the retried task not start another transaction when trying to write to the table because then it would have created new delta directories before writing into bucket file?

**Comment by amoghmargoor** [comment]
@sourabh912 Task retries should not start new transaction. Different tasks of query will get executed in different transactions in that case which will be contradictory to the meaning of transactions.
