### ISSUE TITLE
Add all dynamic partitions touched in write to hive metastore 

### ISSUE THREAD

**Issue by sourabh912** [qubole/spark-acid#44]
For Writes that are going to be touching the dynamic partitions, we are supposed to do 2 things:
1. During taking Lock for write, specify that it is dynamic partition query.
2. For every dynamic partition written into call HiveMetastoreClient.add_dynamic_partition()
First call ensures that a dummy value is put into TXN_COMPONENT table
Second call ensures that dummy value is replaced by actual entry with partitions touched.This ensures that compaction can be called on those partitions. Another use case is that if query gets aborted/failed after taking lock, then dummy value will ensure that cleaner cleans up all the aborted delta files from the table. Without the fix, If the transaction is aborted between openTxn and addPartitions and data has been written on the table the transaction manager will think it's an empty transaction and no cleaning will be done. Aborted delta files will not be read until this transaction is present in TXN tables as aborted transaction. But later when this is removed from TXNS table assuming its an empty transaction, those aborted delta files would still be present leading to issues.

**Comment by amoghmargoor** [comment]
Fixed via 736ffa3d5f68ef65714504f148f8530efd873cec
